name: Feature Request
description: Suggest an idea for this project
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to suggest a new feature!
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What would you like to see added?
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem to Solve
      description: What problem would this feature solve?
    validations:
      required: true